apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- if .Values.name }}
           {{ .Values.name }}
         {{- else }}
           {{ include "config-map.fullname" . }}{{- if .Values.colorname }}-{{ .Values.colorname }}{{- end }}
         {{- end }}
  namespace: app
data:
  base-text: "Ceci est un texte de base non paramétrable"
  additional-text: {{ .Values.additionalText }}