apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app-indianred
  labels:
    app: color-app
    color: indianred
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-app
      color: indianred
  template:
    metadata:
      labels:
        app: color-app
        color: indianred
    spec:
      containers:
      - name: color-app
        image: color-demo:local
        ports:
        - containerPort: 8080
        env:
        - name: COLOR
          value: "indianred"
        # - name: NAME
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.uid
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 1
        #   failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: color-app-indianred
  labels:
    app: color-app
    color: indianred
spec:
  sessionAffinity: None
  ports:
  - port: 10001
    targetPort: 8080
    nodePort: 30001
    name: http
  selector:
    app: color-app
    color: indianred
  type: NodePort
