# Configuration pour l'instance bleue
blue-app:
  enabled: false
  config-map:
    colorname: blue

# Configuration pour l'instance orange
orange-app:
  enabled: false
  config-map:
    colorname: orange

# Configuration pour l'instance violette
purple-app:
  enabled: true

  color-app:
    replicaCount: 3
    color: purple
    fullnameOverride: "purple-app"
    service:
      port: 10003
      nodePort: 30003

  config-map:
    colorname: purple
    additionalText: "PURPLE TEXT"

service:
  type: NodePort
  port: 10005
  targetPort: 8080
  nodePort: 30005
  