# Configuration pour l'instance bleue
blue-app:
  enabled: true

  color-app:
    replicaCount: 1
    color: lightskyblue
    fullnameOverride: "blue-app"
    service:
      port: 10002
      nodePort: 30002
    initContainer:
      enabled: true

  config-map:
    additionalText: "BLUE TEXT"

# Configuration pour l'instance orange
orange-app:
  enabled: true

  color-app:
    replicaCount: 2
    color: coral
    fullnameOverride: "orange-app"
    service:
      port: 10001
      nodePort: 30001
    initContainer:
      enabled: true

  config-map:
    additionalText: "ORANGE TEXT"
